mariadb:
  image: mariadb
  environment:
  - MYSQL_DATABASE=racktables
  - MYSQL_USER=racktables
  - MYSQL_PASSWORD=REPLACE_ME
  - MYSQL_RANDOM_ROOT_PASSWORD=REPLACE_ME
racktables:
  build: racktables
  links:
  - mariadb
  environment:
  - DBHOST=mariadb
  - DBNAME=racktables
  - DBUSER=racktables
  - DBPASS=REPLACE_ME
nginx-echo-headers:
  image: brndnmtthws/nginx-echo-headers
nginx:
  build: nginx-selfsigned-ssl
  links:
  - nginx-echo-headers
  - racktables
  volumes_from:
  - racktables
  volumes:
  - ./nginx-selfsigned-ssl/nginx.conf:/etc/nginx/nginx.conf
  ports:
  - "443:443"
